name: publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn test:only --bail --ci
      - run: yarn publish --non-interactive
        env:
          YARN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
