name: test

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: yarn test --bail --ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.2
